### ISSUE TITLE
Make it possible to define the Class name under which the constants should be defined

### ISSUE THREAD

**Issue by KuSi833** [ailing35/conjure#1]
The [original issue](https://github.com/palantir/conjure/issues/110) proposes the following structure:
```yml
types:
  definitions:
    constants:
      default-package: com.example.foo
      default-wrapper: Constants
      ChannelA:
        docs: "Notification channel for high-priority service notifications"
        type: string
        value: "my:channel"
      ReadOperation:
        docs: "Operation used to enforce read checks"
        type: string
        value: "my-service:read"
```

...where I assume `default-wrapper` defines the class name.
